package com.mdiaz.trxlauncher;
import android.content.*;import android.content.pm.*;import android.graphics.Color;import android.graphics.drawable.Drawable;import android.view.*;import android.widget.*;import java.util.*;
final class AppsScreen extends ScrollView{
 private final MainActivity a;private GridLayout grid;private EditText search;private String filter="";
 AppsScreen(MainActivity c){super(c);a=c;setFillViewport(true);show(0);}
 private void show(int tab){removeAllViews();LinearLayout root=Ui.col(a);root.setPadding(24,18,24,22);addView(root);root.addView(Ui.text(a,"PRECISION APPS",11,Ui.RED,true));root.addView(Ui.text(a,"Every app, without the clutter.",32,Color.WHITE,true));root.addView(Ui.tabs(a,new String[]{"All","Driving","Media","Tools"},tab,this::show),new LinearLayout.LayoutParams(-1,76));search=new EditText(a);search.setHint("Search all apps");search.setTextColor(Color.WHITE);search.setHintTextColor(Ui.SUB_TEXT);search.setBackground(Ui.bg(Ui.CARD,Ui.CARD_STROKE,18,a));search.setPadding(24,0,24,0);root.addView(search,new LinearLayout.LayoutParams(-1,64));grid=new GridLayout(a);grid.setColumnCount(4);root.addView(grid);buildGrid(tab);search.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){filter=s.toString().toLowerCase();applyFilter();}public void afterTextChanged(android.text.Editable e){}});}
 private void buildGrid(int tab){grid.removeAllViews();List<ResolveInfo> apps=a.getPackageManager().queryIntentActivities(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER),0);apps.sort(Comparator.comparing(x->x.loadLabel(a.getPackageManager()).toString().toLowerCase()));for(ResolveInfo info:apps){String label=info.loadLabel(a.getPackageManager()).toString();if(!label.toLowerCase().contains(filter))continue;Drawable icon=info.loadIcon(a.getPackageManager());LinearLayout tile=Ui.col(a);tile.setGravity(android.view.Gravity.CENTER);tile.setPadding(6,10,6,10);tile.setBackground(Ui.bg(Ui.CARD,Ui.CARD_STROKE,16,a));tile.setTag(label);ImageView iv=new ImageView(a);iv.setImageDrawable(icon);tile.addView(iv,new LinearLayout.LayoutParams(Ui.dp(a,46),Ui.dp(a,46)));TextView tv=Ui.text(a,label,10,Color.WHITE,false);tv.setGravity(android.view.Gravity.CENTER);tv.setMaxLines(2);tile.addView(tv);tile.setOnClickListener(v->{Intent i=a.getPackageManager().getLaunchIntentForPackage(info.activityInfo.packageName);if(i!=null)a.startActivity(i);});grid.addView(tile,new GridLayout.LayoutParams(){ {width=0;height=Ui.dp(a,116);columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);setMargins(6,6,6,6);} });}}
 private void applyFilter(){for(int i=0;i<grid.getChildCount();i++){View v=grid.getChildAt(i);Object tag=v.getTag();v.setVisibility(tag!=null&&tag.toString().toLowerCase().contains(filter)?VISIBLE:GONE);}}
}
