package com.mdiaz.trxlauncher;
import android.content.*;import android.graphics.Bitmap;import android.media.MediaMetadata;import android.media.session.*;import android.provider.Settings;import android.service.notification.NotificationListenerService;import java.util.*;
public class MediaAccessService extends NotificationListenerService{
 static volatile String title="No active track",artist="Open a media source";static volatile boolean playing;static volatile Bitmap albumArt;static volatile String sourcePkg;static volatile List<QueueEntry> queue=new ArrayList<>();
 private static volatile MediaController controller;
 static class QueueEntry{String title,artist;Bitmap art;QueueEntry(String t,String a,Bitmap b){title=t;artist=a;art=b;}}
 @Override public void onListenerConnected(){refresh(this);}
 @Override public void onNotificationPosted(android.service.notification.StatusBarNotification n){refresh(this);}
 static boolean hasAccess(Context c){String s=Settings.Secure.getString(c.getContentResolver(),"enabled_notification_listeners");return s!=null&&s.toLowerCase().contains(c.getPackageName().toLowerCase());}
 static void refresh(Context c){if(!hasAccess(c))return;try{MediaSessionManager m=(MediaSessionManager)c.getSystemService(Context.MEDIA_SESSION_SERVICE);List<MediaController> all=m.getActiveSessions(new ComponentName(c,MediaAccessService.class));controller=null;for(MediaController x:all){controller=x;PlaybackState ps=x.getPlaybackState();if(ps!=null&&ps.getState()==PlaybackState.STATE_PLAYING)break;}if(controller==null)return;sourcePkg=controller.getPackageName();MediaMetadata md=controller.getMetadata();PlaybackState ps=controller.getPlaybackState();playing=ps!=null&&ps.getState()==PlaybackState.STATE_PLAYING;if(md!=null){String t=md.getString(MediaMetadata.METADATA_KEY_TITLE),ar=md.getString(MediaMetadata.METADATA_KEY_ARTIST);if(t!=null&&!t.isBlank())title=t;if(ar!=null&&!ar.isBlank())artist=ar;Bitmap art=md.getBitmap(MediaMetadata.METADATA_KEY_ART);if(art==null)art=md.getBitmap(MediaMetadata.METADATA_KEY_ALBUM_ART);albumArt=art;}List<QueueEntry> q=new ArrayList<>();List<MediaSession.QueueItem> items=controller.getQueue();if(items!=null)for(MediaSession.QueueItem item:items){android.media.MediaDescription desc=item.getDescription();String qt=desc.getTitle()!=null?desc.getTitle().toString():"Unknown";String qa=desc.getSubtitle()!=null?desc.getSubtitle().toString():"";Bitmap qb=desc.getIconBitmap();q.add(new QueueEntry(qt,qa,qb));}queue=q;}catch(Throwable ignored){}}
 static void playPause(){try{if(controller==null)return;if(playing)controller.getTransportControls().pause();else controller.getTransportControls().play();playing=!playing;}catch(Throwable ignored){}}
}
